/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package josemotors;

/**
 *
 * @author LuizaCavarcan
 */
public class ManagerMenu extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMenu
     */
    public ManagerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        label = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        buttonAddVehicle = new javax.swing.JButton();
        buttonModifyVehicle = new javax.swing.JButton();
        buttonRemoveVehicle = new javax.swing.JButton();
        listVehicles = new java.awt.List();
        buttonModifyUser = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        buttonAddClient = new javax.swing.JButton();
        buttonModifyClient = new javax.swing.JButton();
        buttonRemoveClient = new javax.swing.JButton();
        listClients = new java.awt.List();
        buttonModifyUser1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        buttonAddEmployee = new javax.swing.JButton();
        buttonModifyEmployee = new javax.swing.JButton();
        buttonRemoveEmployee = new javax.swing.JButton();
        listEmployees = new java.awt.List();
        buttonModifyUser2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        buttonAddSale = new javax.swing.JButton();
        listSales = new java.awt.List();
        buttonModifyUser3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 750));

        label.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jPanel1.setPreferredSize(new java.awt.Dimension(1275, 650));

        buttonAddVehicle.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonAddVehicle.setText("Adicionar Veículo");
        buttonAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddVehicleActionPerformed(evt);
            }
        });

        buttonModifyVehicle.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonModifyVehicle.setText("Modificar Veículo");
        buttonModifyVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyVehicleActionPerformed(evt);
            }
        });

        buttonRemoveVehicle.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonRemoveVehicle.setText("Excluir Veículo");
        buttonRemoveVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveVehicleActionPerformed(evt);
            }
        });

        listVehicles.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        listVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listVehiclesActionPerformed(evt);
            }
        });

        buttonModifyUser.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonModifyUser.setText("Alterar Usuário");
        buttonModifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(listVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonRemoveVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(buttonAddVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonModifyVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(buttonModifyUser, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonModifyVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(buttonRemoveVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(buttonModifyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        label.addTab("Veículos", jPanel1);

        jPanel5.setPreferredSize(new java.awt.Dimension(1275, 650));

        buttonAddClient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonAddClient.setText("Adicionar Cliente");
        buttonAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddClientActionPerformed(evt);
            }
        });

        buttonModifyClient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonModifyClient.setText("Modificar Cliente");
        buttonModifyClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyClientActionPerformed(evt);
            }
        });

        buttonRemoveClient.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonRemoveClient.setText("Excluir Cliente");
        buttonRemoveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveClientActionPerformed(evt);
            }
        });

        listClients.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        listClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClientsActionPerformed(evt);
            }
        });

        buttonModifyUser1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonModifyUser1.setText("Alterar Usuário");
        buttonModifyUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyUser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(listClients, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonRemoveClient, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(buttonAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonModifyClient, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(buttonModifyUser1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listClients, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(buttonAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonModifyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(buttonRemoveClient, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(buttonModifyUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        label.addTab("Clientes", jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(1275, 650));

        buttonAddEmployee.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonAddEmployee.setText("Adicionar Funcionário");
        buttonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddEmployeeActionPerformed(evt);
            }
        });

        buttonModifyEmployee.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonModifyEmployee.setText("Modificar Funcionário");
        buttonModifyEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyEmployeeActionPerformed(evt);
            }
        });

        buttonRemoveEmployee.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonRemoveEmployee.setText("Excluir Funcionário");
        buttonRemoveEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveEmployeeActionPerformed(evt);
            }
        });

        listEmployees.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        listEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEmployeesActionPerformed(evt);
            }
        });

        buttonModifyUser2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonModifyUser2.setText("Alterar Usuário");
        buttonModifyUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyUser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(listEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonRemoveEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(buttonAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonModifyEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(buttonModifyUser2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(buttonAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonModifyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(buttonRemoveEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(buttonModifyUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        label.addTab("Funcionários", jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(1275, 650));

        buttonAddSale.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonAddSale.setText("Adicionar Venda");
        buttonAddSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSaleActionPerformed(evt);
            }
        });

        listSales.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        listSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSalesActionPerformed(evt);
            }
        });

        buttonModifyUser3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        buttonModifyUser3.setText("Alterar Usuário");
        buttonModifyUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyUser3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(listSales, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonAddSale, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(buttonModifyUser3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(listSales, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAddSale, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(buttonModifyUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        label.addTab("Vendas", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listVehiclesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listVehiclesActionPerformed

    private void buttonRemoveVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRemoveVehicleActionPerformed

    private void buttonModifyVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyVehicleActionPerformed

    private void buttonAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddVehicleActionPerformed

    }//GEN-LAST:event_buttonAddVehicleActionPerformed

    private void buttonModifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyUserActionPerformed

    private void buttonAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddClientActionPerformed

    private void buttonModifyClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyClientActionPerformed

    private void buttonRemoveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRemoveClientActionPerformed

    private void listClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listClientsActionPerformed

    private void buttonModifyUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyUser1ActionPerformed

    private void buttonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddEmployeeActionPerformed

    private void buttonModifyEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyEmployeeActionPerformed

    private void buttonRemoveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRemoveEmployeeActionPerformed

    private void listEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEmployeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listEmployeesActionPerformed

    private void buttonModifyUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyUser2ActionPerformed

    private void buttonAddSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddSaleActionPerformed

    private void listSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listSalesActionPerformed

    private void buttonModifyUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyUser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonModifyUser3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddClient;
    private javax.swing.JButton buttonAddEmployee;
    private javax.swing.JButton buttonAddSale;
    private javax.swing.JButton buttonAddVehicle;
    private javax.swing.JButton buttonModifyClient;
    private javax.swing.JButton buttonModifyEmployee;
    private javax.swing.JButton buttonModifyUser;
    private javax.swing.JButton buttonModifyUser1;
    private javax.swing.JButton buttonModifyUser2;
    private javax.swing.JButton buttonModifyUser3;
    private javax.swing.JButton buttonModifyVehicle;
    private javax.swing.JButton buttonRemoveClient;
    private javax.swing.JButton buttonRemoveEmployee;
    private javax.swing.JButton buttonRemoveVehicle;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane label;
    private java.awt.List listClients;
    private java.awt.List listEmployees;
    private java.awt.List listSales;
    private java.awt.List listVehicles;
    // End of variables declaration//GEN-END:variables
}
