import java.awt.*;
import javax.swing.*;

public class Calcula extends javax.swing.JFrame {
    /**
     * Creates new form Calcula
     */
    public Calcula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botaoSomar = new javax.swing.JButton();
        campoN1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoN2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoResultado = new javax.swing.JTextField();
        botaoDivisao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        a = new java.awt.Label();
        botaoSub = new javax.swing.JRadioButton();
        botaoMulti = new javax.swing.JRadioButton();
        botaoMS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 117, 75));
        setPreferredSize(new java.awt.Dimension(1100, 691));

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 691));
        jPanel1.setLayout(null);

        botaoSomar.setBackground(new java.awt.Color(73, 135, 12));
        botaoSomar.setFont(new java.awt.Font("Amiri Quran", 0, 16)); // NOI18N
        botaoSomar.setForeground(new java.awt.Color(138, 92, 21));
        botaoSomar.setText("Somar");
        botaoSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSomarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoSomar);
        botaoSomar.setBounds(580, 420, 120, 108);

        campoN1.setBackground(new java.awt.Color(104, 213, 15));
        campoN1.setFont(new java.awt.Font("Caladea", 0, 16)); // NOI18N
        campoN1.setForeground(new java.awt.Color(179, 59, 189));
        campoN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoN1ActionPerformed(evt);
            }
        });
        jPanel1.add(campoN1);
        campoN1.setBounds(370, 430, 170, 33);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 42, 188));
        jLabel1.setText("Número1:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 440, 68, 19);

        campoN2.setBackground(new java.awt.Color(26, 102, 140));
        campoN2.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        campoN2.setForeground(new java.awt.Color(131, 171, 24));
        jPanel1.add(campoN2);
        campoN2.setBounds(370, 490, 170, 33);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(226, 147, 122));
        jLabel2.setText("Número 2:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 500, 100, 23);

        campoResultado.setBackground(new java.awt.Color(175, 46, 135));
        campoResultado.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        campoResultado.setForeground(new java.awt.Color(184, 213, 26));
        jPanel1.add(campoResultado);
        campoResultado.setBounds(370, 560, 370, 33);

        botaoDivisao.setBackground(new java.awt.Color(122, 201, 79));
        botaoDivisao.setFont(new java.awt.Font("Amiri", 0, 16)); // NOI18N
        botaoDivisao.setForeground(new java.awt.Color(37, 126, 123));
        botaoDivisao.setText("/");
        botaoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDivisaoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoDivisao);
        botaoDivisao.setBounds(10, 10, 140, 170);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 13, 70));
        jLabel3.setText("Resultado:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 570, 77, 20);

        a.setBackground(new java.awt.Color(48, 229, 96));
        a.setFont(new java.awt.Font("Gentium Book Basic", 0, 16)); // NOI18N
        a.setText("-");
        jPanel1.add(a);
        a.setBounds(360, 430, 10, 30);
        a.getAccessibleContext().setAccessibleName("a");

        botaoSub.setBackground(new java.awt.Color(175, 172, 143));
        buttonGroup1.add(botaoSub);
        botaoSub.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        botaoSub.setForeground(new java.awt.Color(152, 71, 74));
        botaoSub.setText("Multiplicação");
        jPanel1.add(botaoSub);
        botaoSub.setBounds(450, 630, 120, 31);

        botaoMulti.setBackground(new java.awt.Color(206, 44, 59));
        buttonGroup1.add(botaoMulti);
        botaoMulti.setFont(new java.awt.Font("Miriam Mono CLM", 3, 16)); // NOI18N
        botaoMulti.setForeground(new java.awt.Color(48, 117, 185));
        botaoMulti.setText("oPÇÃO 1");
        jPanel1.add(botaoMulti);
        botaoMulti.setBounds(820, 30, 95, 29);

        botaoMS.setBackground(new java.awt.Color(185, 146, 222));
        botaoMS.setFont(new java.awt.Font("Alef", 0, 16)); // NOI18N
        botaoMS.setForeground(new java.awt.Color(217, 172, 16));
        botaoMS.setText("Subtração ou multiplicação");
        botaoMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMSActionPerformed(evt);
            }
        });
        jPanel1.add(botaoMS);
        botaoMS.setBounds(10, 440, 230, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 960, 691);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoN1ActionPerformed

    private void botaoSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSomarActionPerformed
        double n1, n2, resultado;
        
        n1 = Double.parseDouble(campoN1.getText());
        n2 = Double.parseDouble(campoN2.getText());
        
        resultado = -n1 + n2;
        
        campoResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_botaoSomarActionPerformed

    private void botaoMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMSActionPerformed
        if(botaoSub.isSelected()) {
            double n1, n2, resultado;
        
            n1 = Double.parseDouble(campoN1.getText());
            n2 = Double.parseDouble(campoN2.getText());

            resultado = -n1 - n2;

            campoResultado.setText(String.valueOf(resultado));
        }
        if(botaoMulti.isSelected()) {
            double n1, n2, resultado;
        
            n1 = Double.parseDouble(campoN1.getText());
            n2 = Double.parseDouble(campoN2.getText());

            resultado = -n1 * n2;

            campoResultado.setText(String.valueOf(resultado));
        }
    }//GEN-LAST:event_botaoMSActionPerformed

    private void botaoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDivisaoActionPerformed
        double n1, n2, resultado;
        
        n1 = Double.parseDouble(campoN1.getText());
        n2 = Double.parseDouble(campoN2.getText());

        resultado = -n1 / n2;

        campoResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_botaoDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcula().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label a;
    private javax.swing.JButton botaoDivisao;
    private javax.swing.JButton botaoMS;
    private javax.swing.JRadioButton botaoMulti;
    private javax.swing.JButton botaoSomar;
    private javax.swing.JRadioButton botaoSub;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoN1;
    private javax.swing.JTextField campoN2;
    private javax.swing.JTextField campoResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
